# =================================
#| DragonProxy konfigurace  |
#|       A BytePowered Team        |
# =================================
# https://GitHub.com/DragonetMC/DragonProxy/wiki

# Jazykovy soubor
# Vychozi = English
lang: default


# Na jake IP a portu ma proxy hledat pripojeni
# IP adresa 0.0.0.0 znamena hledat na vsech dostupnych adresach
udp_bind_ip: '0.0.0.0'
udp_bind_port: 19132


# MOTD (Zprava dne) ktera bude zobrazena na v server listu
motd: '&aServer by DragonProxy'


# Na jaky server se ma proxy automaticky pripojit
# Jmena serveru si muzes nastevit hned v dalsim nastaveni
default_server: 'muj_pc_server'


# Seznam konfiguraci vzdalenych serveru
# Upozorneni: pouzivej mezery misto tabulatoru jako posun radku
remote_servers:
  muj_pc_server:
    # Dalsi radek indikuje, ze se jedna o java edition server
    !!org.dragonet.proxy.DesktopServer
    # Hypixel je dost znamy server
    # tak ho pojdme zkusit! ;)
    remote_addr: 'mc.hypixel.net'
    remote_port: 25565
  muj_pe_server:
    # Dalsi radek indikuje, ze se jedna o bedrock edition server
    !!org.dragonet.proxy.PocketServer
    remote_addr: 'your.packets.server.com'
    remote_port: 19132


# Prihlasovaci mody serveru
# online  : Tradicni prihlasovaci obrazovka Dragon Proxy
# offline : Pripoji te na server v offline modu, coz brani pripojeni
#           na servery jako je Hypixel.
mode: online


# Herni prefix pro prikazy. Vychozi prefix v minecraftu je "/"
command_prefix: '/'


# Jak hodne hracu se muze do proxy pripojit najednou
# Pouzij -1 pro neomezeny pocet
max_players: -1


# Mame ukladat vystup z konzole do souboru?
log_console: true


# Jak hodne vlaken bude zpracovavat minecraft packety? Proved zmeny jen kdyz vis, co delas.
# Doporuceno nejmene 8 vlaken.
# Pokud softwre ppouzivas doma, muzes hodnotu snizit treba na 12 nebo 8.
thread_pool_size: 16